---
- name: Generate a Self Signed certificate
  block:      
    - openssl_privatekey:
        path: "{{ mesos_ssl_key_file }}"

    - openssl_csr:
        path: "{{ mesos_ssl_csr_file }}"
        privatekey_path: "{{ mesos_ssl_key_file }}"

    - openssl_certificate:
        provider: selfsigned
        path: "{{ mesos_ssl_cert_file }}"
        privatekey_path: "{{ mesos_ssl_key_file }}"
        csr_path: "{{ mesos_ssl_csr_file }}"
  when: mesos_ssl_cert_gen == "self_signed"

- include_role:
    name: geerlingguy.certbot
  vars:  
    certbot_auto_renew: true
    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_admin_email: "{{ mesos_certbot_admin_email }}"
    certbot_create_standalone_stop_services: []
    certbot_certs:
      - domains:
          - "{{ mesos_master_dns_name }}"  
  when: mesos_ssl_cert_gen == "letsencrypt"    

