---
- name: Check if REX-Ray is installed
  command: "{{rexray_check_command}}"
  register: rexray_check
  failed_when: rexray_check.rc > 1
  changed_when: false


- name: Download REX-Ray package to local file
  get_url:
    url="{{ rexray_pkg_url }}/{{ rexray_channel }}/{{ rexray_version }}/rexray-rexray-{{ rexray_version }}-{{ ansible_architecture }}.{{rexray_package_type}}"
    dest=/tmp
  when: rexray_check.rc == 1

- name: Install REX-Ray .deb
  apt: deb="/tmp/rexray-rexray-{{ rexray_version }}-{{ ansible_architecture }}.{{rexray_package_type}}" state=present
  when: rexray_check.rc == 1 and ansible_distribution == 'Ubuntu'

- name: Install REX-Ray .rpm
  yum: name="/tmp/rexray-rexray-{{ rexray_version }}-{{ ansible_architecture }}.{{rexray_package_type}}" state=present
  when: rexray_check.rc == 1 and ansible_os_family == 'RedHat'

- name: Delete temporary file
  file: path="/tmp/rexray-rexray-{{ rexray_version }}-{{ ansible_architecture }}.{{rexray_package_type}}" state=absent
  when: rexray_check.rc == 1

- name: Create config file directory
  file: path=/etc/rexray state=directory mode=0755 owner=root group=root

- name: Add rexray config file
  template: src=rexray-conf.j2 dest=/etc/rexray/config.yml mode=0755 owner=root group=root
  notify: restart rexray

- name: ensure rexray is running
  service:
    name: rexray
    state: started
