- name: create log directory  
  file:
    path: "{{ mesos_log_dir }}"
    state: directory
    mode: 0755
  tags:
    - mesos-master
    - mesos-slave

- include: master.yml
  when: mesos_install_mode == "master"

- include: slave.yml
  when: mesos_install_mode == "slave"
